name: Scraper
on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Scrape
        run: ./scraper.sh
        working-directory: ./scraper

      - name: Save
        uses: actions/cache/save@v4
        with:
          path: ./scraper/out
          key: this_is_a_cool_key